title: Tester Blog Site
author: Joseph Edwards
theme: jekyll-theme-slate
description: > # this means to ignore newlines until "baseurl:"
  An introductory blog site to mess around with how pages and
  Jekyll work. There is no content of interest on this site,
  it is merely a place for me to test styles to see what I
  like and what works best.

# social links
twitter_username: JoeDEdwards # DO NOT include the @ character, or else the build will fail!
github_username:  Joseph-Edwards # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
